version: "3.8"
services:
  web:
    build:
      context: .
      target: dev
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb-local
    links:
      - "dynamodb-local"
    environment:
      # these are needed for the aws skd in node, but you don't need real creds
      AWS_ACCESS_KEY_ID: "DUMMYIDEXAMPLE"
      AWS_SECRET_ACCESS_KEY: "DUMMYEXAMPLEKEY"
      AWS_REGION: "us-east-2"
      DB_ENDPOINT: "http://dynamodb-local:8000"
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -optimizeDbBeforeStartup -dbPath ./data -port 8000"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
